---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 35038.
--- DateTime: 2025/11/23 15:10
---
--- 优惠券id
local voucherId = ARGV[1]
--- 用户id
local userId = ARGV[2]
-- 订单id
local orderId = ARGV[3]
-- 优惠券库存key
local stockKey = "seckill:stock:" .. voucherId
-- 订单key
local orderKey = "seckill:order:" .. voucherId
-- 判断库存是否充足
if (tonumber(redis.call("get", stockKey)) < 1) then
    -- 库存不足
    return 1
end
-- 判断用户是否重复下单
if (redis.call("sismember", orderKey, userId) == 1) then
    -- 用户重复下单
    return 2
end
-- 库存充足，用户没有重复下单 减库存，添加订单
redis.call("incrby", stockKey, -1)
redis.call("sadd", orderKey, userId)
--  发消息到队列
redis.call("xadd", "stream.orders", "*", "userId", userId, "voucherId", voucherId, "id", orderId)
return 0