---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 35038.
--- DateTime: 2025/11/23 12:46
---
-- 比较线程中的锁与锁的标示是否一致
if (redis.call("get", KEYS[1]) == ARGV[1]) then
    return redis.call("del", KEYS[1])
end
return 0
